### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by Pritish9124** [knight-rider1609/MultiProgressBar#3]
0:25: AAPT: error: resource attr/enlarge (aka com.okcl.awareness:attr/enlarge) not found.
I guess you missed the tag format for enlarge. 
Please review it. 
Thanks for the awesome progressbar

**Comment by ohito-venteny** [comment]
hi guys, any solution?

**Comment by EderDominguez** [comment]
+1

**Comment by vikram-kadam** [comment]
Same issue

**Comment by knight-rider1609** [comment]
This is now resolved.
